# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\x12\x05proto\"}\n\tDetection\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\twebcam_id\x18\x02 \x01(\t\x12\x10\n\x08\x62uilding\x18\x03 \x01(\t\x12\x16\n\x0eperson_counter\x18\x04 \x01(\x05\x12\x14\n\x0cvideo_stream\x18\x05 \x01(\x0c\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"\x1e\n\x10\x44\x65tectionRequest\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x11\x44\x65tectionResponse\x12#\n\tdetection\x18\x01 \x01(\x0b\x32\x10.proto.Detection\"(\n\x13\x44\x65tectionResponseOK\x12\x11\n\tprocessed\x18\x01 \x01(\t2\x7f\n\rDetectionCRUD\x12\x38\n\x03Get\x12\x17.proto.DetectionRequest\x1a\x18.proto.DetectionResponse\x12\x34\n\x04Post\x12\x10.proto.Detection\x1a\x1a.proto.DetectionResponseOKb\x06proto3')
)




_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='proto.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.Detection.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='webcam_id', full_name='proto.Detection.webcam_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='building', full_name='proto.Detection.building', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='person_counter', full_name='proto.Detection.person_counter', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_stream', full_name='proto.Detection.video_stream', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='proto.Detection.timestamp', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=149,
)


_DETECTIONREQUEST = _descriptor.Descriptor(
  name='DetectionRequest',
  full_name='proto.DetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.DetectionRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=181,
)


_DETECTIONRESPONSE = _descriptor.Descriptor(
  name='DetectionResponse',
  full_name='proto.DetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detection', full_name='proto.DetectionResponse.detection', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=239,
)


_DETECTIONRESPONSEOK = _descriptor.Descriptor(
  name='DetectionResponseOK',
  full_name='proto.DetectionResponseOK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='processed', full_name='proto.DetectionResponseOK.processed', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=281,
)

_DETECTIONRESPONSE.fields_by_name['detection'].message_type = _DETECTION
DESCRIPTOR.message_types_by_name['Detection'] = _DETECTION
DESCRIPTOR.message_types_by_name['DetectionRequest'] = _DETECTIONREQUEST
DESCRIPTOR.message_types_by_name['DetectionResponse'] = _DETECTIONRESPONSE
DESCRIPTOR.message_types_by_name['DetectionResponseOK'] = _DETECTIONRESPONSEOK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), {
  'DESCRIPTOR' : _DETECTION,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:proto.Detection)
  })
_sym_db.RegisterMessage(Detection)

DetectionRequest = _reflection.GeneratedProtocolMessageType('DetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:proto.DetectionRequest)
  })
_sym_db.RegisterMessage(DetectionRequest)

DetectionResponse = _reflection.GeneratedProtocolMessageType('DetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:proto.DetectionResponse)
  })
_sym_db.RegisterMessage(DetectionResponse)

DetectionResponseOK = _reflection.GeneratedProtocolMessageType('DetectionResponseOK', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONRESPONSEOK,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:proto.DetectionResponseOK)
  })
_sym_db.RegisterMessage(DetectionResponseOK)



_DETECTIONCRUD = _descriptor.ServiceDescriptor(
  name='DetectionCRUD',
  full_name='proto.DetectionCRUD',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=283,
  serialized_end=410,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='proto.DetectionCRUD.Get',
    index=0,
    containing_service=None,
    input_type=_DETECTIONREQUEST,
    output_type=_DETECTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Post',
    full_name='proto.DetectionCRUD.Post',
    index=1,
    containing_service=None,
    input_type=_DETECTION,
    output_type=_DETECTIONRESPONSEOK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTIONCRUD)

DESCRIPTOR.services_by_name['DetectionCRUD'] = _DETECTIONCRUD

# @@protoc_insertion_point(module_scope)
